// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQtpNHPnS5bWnhtmQ7bSDOtKGewzQ1-qE',
    appId: '1:184061360599:web:76f7675e3a9762ee827392',
    messagingSenderId: '184061360599',
    projectId: 'flutter-chat-app-59478',
    authDomain: 'flutter-chat-app-59478.firebaseapp.com',
    storageBucket: 'flutter-chat-app-59478.appspot.com',
    measurementId: 'G-NT9554LL8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfMN_OnmJwonkDtPzDsuLE61knVg5425k',
    appId: '1:184061360599:android:2c932dea20887f77827392',
    messagingSenderId: '184061360599',
    projectId: 'flutter-chat-app-59478',
    storageBucket: 'flutter-chat-app-59478.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD3DBOkpYTEoTJ55IgT5XOP2H5vV20W6k',
    appId: '1:184061360599:ios:a5a624287e61c6e2827392',
    messagingSenderId: '184061360599',
    projectId: 'flutter-chat-app-59478',
    storageBucket: 'flutter-chat-app-59478.appspot.com',
    iosBundleId: 'com.example.chatCraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD3DBOkpYTEoTJ55IgT5XOP2H5vV20W6k',
    appId: '1:184061360599:ios:73a1015d8f27a1bc827392',
    messagingSenderId: '184061360599',
    projectId: 'flutter-chat-app-59478',
    storageBucket: 'flutter-chat-app-59478.appspot.com',
    iosBundleId: 'com.example.chatCraft.RunnerTests',
  );
}
